import { Response, NextFunction } from 'express';
import { RowDataPacket } from 'mysql2';
import { pool } from '../db/connection';
import { AuthRequest } from './requireAuth';

// Uploaded filenames are always generated by the server (see minis.ts): a
// timestamp, random letters, and an image extension. Anything else — slashes,
// "..", hidden files — is refused before it reaches the disk or the database.
const SAFE_UPLOAD_NAME = /^\/[A-Za-z0-9-]+\.(png|jpg|gif|webp)$/;

// Mounted under /uploads, after requireAuth. A photo is only served to members
// of the collection its mini belongs to — same rule as the mini itself — so a
// leaked or guessed link is useless to anyone outside that group. Everyone
// else gets 404, as if the photo didn't exist.
export async function requireImageAccess(req: AuthRequest, res: Response, next: NextFunction): Promise<void> {
  if (!SAFE_UPLOAD_NAME.test(req.path)) {
    res.status(404).json({ error: 'Not found' });
    return;
  }

  try {
    const [rows] = await pool.execute<RowDataPacket[]>(
      `SELECT 1 AS found
       FROM mini_images mi
       JOIN minis m ON m.id = mi.mini_id
       JOIN collection_memberships cm ON cm.collection_id = m.collection_id
       WHERE mi.image_path = ? AND cm.user_id = ?
       LIMIT 1`,
      [`/uploads${req.path}`, req.user!.userId]
    );

    if (rows.length === 0) {
      res.status(404).json({ error: 'Not found' });
      return;
    }
    next();
  } catch (err: unknown) {
    console.error(err);
    res.status(500).json({ error: 'Server error' });
  }
}
